nom: loop over images with 'docker pull'
podman supported multiple images, but docker does not

diff --git a/bin/nom b/bin/nom
--- a/bin/nom
+++ b/bin/nom
@@ -37,15 +37,11 @@ cmd_diff() {
 }
 
 cmd_prepull() {
-  local images driver node nodes
+  local images node nodes
 
   mapfile -t images < <(nomad run -output "$1" |
     jq -r '.Job.TaskGroups | map(.Tasks[].Config.image) | unique[]')
   [[ $images ]] || return
-
-  # This assumes the same driver for all images, but generally speaking we're
-  # always using docker.
-  driver=$(nomad run -output "$1" | jq -r '.Job.TaskGroups[0].Tasks[0].Driver')
 
   mapfile -t nodes < <(nomad node status -json |
     jq -r --argjson dcs "$(nomad run -output "$1" | jq '.Job.Datacenters')" \
@@ -53,22 +49,21 @@ cmd_prepull() {
           .[] | (. as $root | select($dcs == ["*"] or any($dcs[]; . == $root.Datacenter))) | .Name
        ] | sort | .[]')
 
-  declare -A driver_argv=(
-    [docker]="docker"
-  )
-
   printf 'Pulling image(s) to nodes: %s\n' "${nodes[*]}"
   printf ' * %s\n' "${images[@]}"
 
   declare -A logs
   for node in "${nodes[@]}"; do
     (
-      if ssh "$node".node.home ${driver_argv[$driver]} pull "${images[@]}" &>/tmp/prepull.$node; then
-        echo "SUCCESS: prepull done on $node"
-      else
-        echo "ERROR: prepull on $node failed; check /tmp/prepull.$node"
-        false
-      fi
+      for image in "${images[@]}"; do
+        logfile=/tmp/prepull.$node
+        if ssh "$node".node.home docker pull "$image" &>"$logfile"; then
+          echo "SUCCESS: [$image] prepull done on $node"
+        else
+          echo "ERROR: prepull on $node failed; check $logfile"
+          exit 1
+        fi
+      done
     ) &
     logs[$node]=$!
   done
