refresh-vault-certs: split into two part script

diff --git a/bin/refresh-vault-certs b/bin/refresh-vault-certs
--- a/bin/refresh-vault-certs
+++ b/bin/refresh-vault-certs
@@ -1,6 +1,64 @@
 #!/bin/bash
 
-if ! command -v vault >dev/null; then
+# fetch the intermediate ca_chain (needed for the listener)
+
+write_new_certs_to_vault() {
+  vault read -format=raw pki_int/ca_chain >home-ca.pem
+
+  for i in 0 1 2; do
+    echo "=> Issuing new certificate for vault on nomad$i.node.home"
+
+    vault write \
+      -format=json pki_int/issue/vault-servers \
+      common_name=vault.service.home \
+      ip_sans=10.0.100.10$i,127.0.0.1 \
+      alt_names=active.vault.service.home,standby.vault.service.home,localhost \
+      ttl=4380h | tee nomad$i.node.home.certs
+
+    echo ' -> extracting...'
+    # extract certificate
+    jq -r '.data.certificate' "nomad$i.node.home.certs" >"vault$i.tls.crt"
+
+    # extract private key
+    jq -r '.data.private_key' "nomad$i.node.home.certs" >"vault$i.tls.key"
+
+    # create listener certificate chain
+    cat 'home-ca.pem' "vault$1.tls.crt" >"listener.vault$i.pem"
+
+    echo ' -> writing to vault...'
+    # write them all to vault
+    vault kv put \
+        kv/tls/vault/nomad$i.node.home \
+        private_key=@vault$i.tls.key \
+        certificate=@vault$i.tls.crt
+        # listener=@listener.vault$i.pem
+    echo ' -> SUCCESS'
+  done
+}
+
+teeout() {
+  sudo tee "/opt/vault/tls/$1" >/dev/null
+}
+
+deploy_certs_from_vault() {
+  local hostname=$1
+
+  if [[ -z $hostname ]]; then
+    echo 'ERROR: no hostname provided'
+    return 1
+  fi
+
+  vault read -format=raw pki_int/ca_chain | teeout home-ca.pem
+
+  vault kv get -format=json kv/tls/vault/$hostname |
+      tee >(jq -r '.data.data.private_key | rtrimstr("\n")' | teeout tls.key) \
+      tee >(jq -r '.data.data.certificate | rtrimstr("\n")' | teeout tls.cert)
+
+  cat /opt/vault/tls/tls.cert /opt/vault/tls/home-ca.pem |
+      teeout listener.pem
+}
+
+if ! command -v vault >/dev/null; then
   echo "ERROR: no vault binary found"
   exit 1
 fi
@@ -10,37 +68,17 @@ if ! vault token lookup &>/dev/null; then
   exit 1
 fi
 
-# vault read pki_int/ca_chain is brokeass
-curl -s http://172.17.0.1:8200/v1/pki_int/ca_chain >home-ca.pem
+cmd=$1
+shift
 
-for i in 0 1 2; do
-  echo "=> Issuing new certificate for vault on nomad$i.node.home"
-
-  vault write \
-    -format=json pki_int/issue/vault-servers \
-    common_name=vault.service.home \
-    ip_sans=10.0.100.10$i,127.0.0.1 \
-    alt_names=active.vault.service.home,standby.vault.service.home,localhost \
-    ttl=4380h | tee nomad$i.node.home.certs
-
-  echo ' -> extracting...'
-  # extract certificate
-  jq -r '.data.certificate' "nomad$i.node.home.certs" >"vault$i.tls.crt"
-
-  # extract private key
-  jq -r '.data.private_key' "nomad$i.node.home.certs" >"vault$i.tls.key"
-
-  # create listener certificate chain
-  cat 'home-ca.pem' "vault$1.tls.crt" >"listener.vault$i.pem"
-
-  echo ' -> writing to vault...'
-  # write them all to vault
-  vault kv put \
-      kv/tls/vault/nomad$i.node.home \
-      private_key=@vault$i.tls.key \
-      certificate=@vault$i.tls.crt \
-      listener=@listener.vault$i.pem
-  echo ' -> SUCCESS'
-done
-
-# extract them
+case $cmd in
+  generate)
+    write_new_certs_to_vault "$@"
+    ;;
+  deploy)
+    deploy_certs_from_vault "$@"
+    ;;
+  *)
+    echo "ERROR: unknown command: $cmd"
+    ;;
+esac
